from __future__ import annotations

from dataclasses import FrozenInstanceError, replace

import pytest

from sds200.scanner_display_layout import (
    DisplayMappingIssueKind,
    DisplayProfilePosition,
    DisplayRegionKind,
    DisplaySlotSelection,
    DisplayTextAlignment,
    resolve_scanner_display_screen,
    scanner_display_layout,
)
from sds200.scanner_display_profile import (
    ScannerDisplayColor,
    ScannerDisplayMode,
    ScannerDisplayOptionGroup,
    parse_scanner_display_profile,
)

# Independent source-table counts, not generated by the implementation.
SIMPLE_OPTIONS = {1: 3, 2: 2, 3: 8, 4: 10}
SIMPLE_COLORS = {1: 6, 2: 3, 3: 8, 4: 2, 5: 10, 6: 6, 7: 5}
DETAIL_OPTIONS = {1: 3, 2: 12, 3: 6, 4: 10}
DETAIL_COLORS = {1: 9, 2: 3, 3: 6, 4: 12, 5: 10, 6: 5, 7: 5}
SPECIAL_OPTIONS = {2: 8, 3: 6, 4: 10}
SPECIAL_COLORS = {1: 11, 3: 6, 4: 8, 5: 10, 6: 5, 7: 5}


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_source_html_alignment_and_photographed_name_line_counts(mode):
    regions = {region.id: region for region in scanner_display_layout(mode).regions}
    simple = mode.layout_ids[0] <= 2
    scan = mode.layout_ids[0] <= 4
    for name in ("function", "signal", "battery", "key_lock", "direction", "option_1", "option_8"):
        assert regions[name].alignment is DisplayTextAlignment.CENTER
    for name in ("option_a_1", "option_b_1"):
        assert regions[name].alignment is (
            DisplayTextAlignment.CENTER if simple else DisplayTextAlignment.LEFT
        )
    if scan:
        for name in ("system", "department", "channel"):
            assert regions[name].alignment is DisplayTextAlignment.LEFT
            assert regions[name].name_lines == (2 if simple else 1)
            assert regions[f"{name}_option"].alignment is DisplayTextAlignment.LEFT
    if not simple:
        for name in ("information_1", "information_2", "information_3", "option_c_1"):
            assert regions[name].alignment is DisplayTextAlignment.LEFT
    for name in ("soft_key_1", "soft_key_2", "soft_key_3", "icon_1"):
        assert regions[name].alignment is DisplayTextAlignment.CENTER


def synthetic_profile():
    records = ["DisplayOption\t\t\t\t\t\tDEC\t\t\t\t\tOff\tAFS\tCOLOR"]
    for layout, color_layout, options, colors in (
        (1, 1, SIMPLE_OPTIONS, SIMPLE_COLORS),
        (2, 6, SIMPLE_OPTIONS, SIMPLE_COLORS),
        (3, 2, DETAIL_OPTIONS, DETAIL_COLORS),
        (4, 7, DETAIL_OPTIONS, DETAIL_COLORS),
        (5, 3, SPECIAL_OPTIONS, SPECIAL_COLORS),
        (6, 4, SPECIAL_OPTIONS, SPECIAL_COLORS),
        (7, 5, SPECIAL_OPTIONS, SPECIAL_COLORS),
    ):
        for group, count in options.items():
            records.append(
                "\t".join(
                    [
                        "DispOptItems",
                        f"DispOptId={group}",
                        f"DispLayoutId={layout}",
                        *(f"Token_{layout}_{group}_{position}" for position in range(1, count + 1)),
                    ]
                )
            )
        for group, count in colors.items():
            pairs = [
                value
                for position in range(1, count + 1)
                for value in (f"{color_layout:02x}{group:02x}{position:02x}", "000000")
            ]
            records.append(
                "\t".join(
                    [
                        "DispColors",
                        f"DispColorId={group}",
                        f"ColorLayoutId={color_layout}",
                        *pairs,
                    ]
                )
            )
    return parse_scanner_display_profile("\r\n".join(records).encode("ascii"))


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_every_grid_cell_has_exactly_one_region(mode):
    layout = scanner_display_layout(mode)
    assert (layout.rows, layout.columns) == (20, 30)
    assert len({region.id for region in layout.regions}) == len(layout.regions)
    occupied = set()
    for region in layout.regions:
        assert region.rows > 0 and region.columns > 0
        for row in range(region.row, region.row + region.rows):
            for column in range(region.column, region.column + region.columns):
                assert 0 <= row < 20 and 0 <= column < 30
                assert (row, column) not in occupied, region.id
                occupied.add((row, column))
    assert len(occupied) == 600


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_all_qualified_profile_positions_are_unique_and_complete(mode):
    layout = scanner_display_layout(mode)
    for attribute, sizes in (
        ("option", layout.option_group_sizes),
        ("color", layout.color_group_sizes),
    ):
        positions = [
            getattr(region, attribute)
            for region in layout.regions
            if getattr(region, attribute) is not None
        ]
        assert len(positions) == len(set(positions))
        assert set(positions) == {
            DisplayProfilePosition(group, position)
            for group, count in sizes
            for position in range(1, count + 1)
        }


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_distinct_layout_and_color_namespaces_map_without_aliasing(mode):
    profile = synthetic_profile()
    screen = resolve_scanner_display_screen(profile, mode)
    layout_id, color_id = mode.layout_ids
    assert screen.profile_revision == profile.revision
    assert screen.color_mode == "COLOR"
    for resolved in screen.regions:
        option, color = resolved.region.option, resolved.region.color
        if option is not None:
            assert resolved.token == f"Token_{layout_id}_{option.group}_{option.position}"
            assert resolved.selection is DisplaySlotSelection.CONFIGURED
        else:
            assert resolved.token is None
            assert resolved.selection is DisplaySlotSelection.FIXED
        if color is not None:
            assert resolved.stored_color == ScannerDisplayColor(
                f"{color_id:02x}{color.group:02x}{color.position:02x}",
                "000000",
            )
        else:
            assert resolved.stored_color is None
    expected = [] if layout_id in (1, 2) else [DisplayMappingIssueKind.UNQUALIFIED_COLOR_ORDER]
    assert [issue.kind for issue in screen.issues] == expected


@pytest.mark.parametrize("mode", list(ScannerDisplayMode)[2:])
def test_small_options_seven_eight_are_fifth_sixth_tokens_without_guessed_colors(mode):
    profile = synthetic_profile()
    resolved = {
        item.region.id: item for item in resolve_scanner_display_screen(profile, mode).regions
    }
    for region_id, position in (("option_7", 5), ("option_8", 6)):
        assert resolved[region_id].region.option == DisplayProfilePosition(3, position)
        assert resolved[region_id].stored_color is None
    assert "option_5" not in resolved and "option_6" not in resolved
    assert resolved["option_c_1"].region.option.position == (11 if mode.layout_ids[0] < 5 else 7)
    # Even eight supplied pairs cannot resolve the conflicting table/grid order.
    colors = tuple(
        replace(group, colors=group.colors + group.colors[:2])
        if group.color_layout_id == mode.layout_ids[1] and group.group_id == 3
        else group
        for group in profile.color_groups
    )
    screen = resolve_scanner_display_screen(replace(profile, color_groups=colors), mode)
    assert all(
        item.stored_color is None
        for item in screen.regions
        if item.region.id.startswith("option_") and item.region.option.group == 3
    )


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_inversion_is_explicit_metadata_not_mutated_stored_colors(mode):
    screen = resolve_scanner_display_screen(synthetic_profile(), mode)
    reversed_ids = {item.region.id for item in screen.regions if item.region.reverse_colors}
    expected = {"function", "soft_key_1", "soft_key_2", "soft_key_3"}
    if mode.layout_ids[0] >= 5:
        expected.add("hold")
    assert reversed_ids == expected
    assert all(
        item.stored_color.background == "000000"
        for item in screen.regions
        if item.region.reverse_colors
    )


@pytest.mark.parametrize("mode", list(ScannerDisplayMode))
def test_missing_or_wrong_sized_groups_do_not_shift_or_partially_map(mode):
    profile = synthetic_profile()
    layout_id, color_id = mode.layout_ids
    missing = replace(
        profile,
        option_groups=tuple(
            group
            for group in profile.option_groups
            if not (group.layout_id == layout_id and group.group_id == 2)
        ),
        color_groups=tuple(
            group
            for group in profile.color_groups
            if not (group.color_layout_id == color_id and group.group_id == 4)
        ),
    )
    screen = resolve_scanner_display_screen(missing, mode)
    for item in screen.regions:
        if item.region.option is not None and item.region.option.group == 2:
            assert item.selection is DisplaySlotSelection.MISSING_GROUP
            assert item.token is None and item.stored_color is None
    for delta in (-1, 1):
        malformed = replace(
            profile,
            option_groups=tuple(
                replace(group, items=group.items[:-1] if delta < 0 else group.items + ("Extra",))
                if group.layout_id == layout_id and group.group_id == 2
                else group
                for group in profile.option_groups
            ),
            color_groups=tuple(
                replace(
                    group,
                    colors=group.colors[:-1] if delta < 0 else group.colors + group.colors[:1],
                )
                if group.color_layout_id == color_id and group.group_id == 4
                else group
                for group in profile.color_groups
            ),
        )
        screen = resolve_scanner_display_screen(malformed, mode)
        for item in screen.regions:
            if item.region.option is not None and item.region.option.group == 2:
                assert item.selection is DisplaySlotSelection.INVALID_GROUP_SIZE
                assert item.token is None and item.stored_color is None


def test_blank_empty_and_unknown_tokens_are_distinct():
    profile = synthetic_profile()
    profile = replace(
        profile,
        option_groups=tuple(
            ScannerDisplayOptionGroup(1, 1, ("", "Empty", "FutureToken"))
            if group.layout_id == 1 and group.group_id == 1
            else group
            for group in profile.option_groups
        ),
    )
    screen = resolve_scanner_display_screen(profile, ScannerDisplayMode.SIMPLE_CONVENTIONAL)
    items = [
        item
        for item in screen.regions
        if item.region.option is not None and item.region.option.group == 1
    ]
    assert [item.selection for item in items] == [
        DisplaySlotSelection.BLANK,
        DisplaySlotSelection.EMPTY,
        DisplaySlotSelection.CONFIGURED,
    ]
    assert [item.token for item in items] == ["", "Empty", "FutureToken"]


def test_unexpected_group_is_reported_not_used_or_removed_from_profile():
    profile = synthetic_profile()
    extra = ScannerDisplayOptionGroup(5, 1, ("DoNotUse",))
    profile = replace(profile, option_groups=profile.option_groups + (extra,))
    screen = resolve_scanner_display_screen(profile, ScannerDisplayMode.SEARCH_CLOSE_CALL)
    assert any(
        issue.namespace == "option"
        and issue.group == 1
        and issue.kind is DisplayMappingIssueKind.UNEXPECTED_GROUP
        for issue in screen.issues
    )
    assert all(item.token != "DoNotUse" for item in screen.regions)
    assert extra in profile.option_groups


@pytest.mark.parametrize("color_mode", ["COLOR", "BLACK", "WHITE"])
def test_color_mode_is_preserved_without_invented_transform(color_mode):
    profile = synthetic_profile()
    profile = replace(profile, options=replace(profile.options, color_mode=color_mode))
    screen = resolve_scanner_display_screen(profile, ScannerDisplayMode.SIMPLE_TRUNK)
    assert screen.color_mode == color_mode
    assert screen.regions[0].stored_color == ScannerDisplayColor("060601", "000000")


def test_fixed_regions_are_not_guessed_as_option_values_or_controls():
    screen = resolve_scanner_display_screen(synthetic_profile(), ScannerDisplayMode.WEATHER)
    primary = next(item for item in screen.regions if item.region.id == "primary_1")
    assert primary.selection is DisplaySlotSelection.FIXED and primary.token is None
    assert primary.region.kind is DisplayRegionKind.INFORMATION
    with pytest.raises(FrozenInstanceError):
        screen.color_mode = "WHITE"
    with pytest.raises(ValueError, match="explicit"):
        scanner_display_layout("weather")
