#!/usr/bin/env python3
"""Generate checked-in HA assets from the shared validated browser projection.

No user profile, live data, credentials or installed HA files are read or written.
Use --check in tests/CI; ordinary invocation rewrites only generated repo assets.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from sds200.scanner_display_web import scanner_display_browser_contract

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/sds200/web_assets"
THEMES = ROOT / "src/sds200/themes/home-assistant"
START = "// BEGIN GENERATED SHARED INGRESS\n"
END = "// END GENERATED SHARED INGRESS\n"


def outputs() -> dict[Path, str]:
    shared = (ASSETS / "home-assistant-ingress.js").read_text()
    web = (ASSETS / "mimic-sds.js").read_text()
    # This prefix is the exact WebUI decoder, safe DOM renderer and bounded reader.
    # Fail if its explicit boundary moves; never maintain a second protocol copy.
    boundary = (
        "  function create({host, standard, url, request, "
        "supplementalContext = null, supplementalRoot = null}) {"
    )
    assert web.count(boundary) == 1
    core = web.split(boundary)[0]
    core = core.replace(
        "__SDSCTL_MIMIC_CONTRACT__",
        json.dumps(scanner_display_browser_contract(), separators=(",", ":")),
    )
    card = "// Generated by scripts/build_mimic_lovelace.py; edit source assets.\n"
    # The pure guard is private to this resource; never overwrite a WebUI/global
    # guard when multiple resource versions coexist. Constructor opt-in only.
    supplemental = (ASSETS / "mimic-supplemental.js").read_text()
    export = "window.sdsctlSupplemental = Object.freeze"
    assert supplemental.count("(() => {") == supplemental.count(export) == 1
    supplemental = supplemental.replace("(() => {", "const sdsctlCardSupplemental = (() => {")
    supplemental = supplemental.replace(export, "return Object.freeze")
    card += core + shared + supplemental + (ASSETS / "mimic-sds-card.js").read_text() + "\n})();\n"
    waterfall_path = THEMES / "waterfall/sds200-waterfall-card.js"
    waterfall = waterfall_path.read_text()
    assert waterfall.count(START) == waterfall.count(END) == 1
    waterfall = waterfall.split(START)[0] + START + shared + END + waterfall.split(END)[1]
    generated = {
        THEMES / "mimic-sds/sds200-mimic-card.js": card,
        waterfall_path: waterfall,
    }
    imports = []
    for identifier in ("compact", "sds200-display", "waterfall", "mimic-sds"):
        path = THEMES / identifier / "manifest.json"
        manifest = json.loads(path.read_text())
        module = THEMES / identifier / manifest["module"]
        payload = generated.get(module, module.read_text() if module.exists() else "")
        digest = hashlib.sha256(payload.encode()).hexdigest()
        manifest["resource_url"] = f"/local/sds200/{manifest['installed_filename']}?v={digest}"
        generated[path] = json.dumps(manifest, indent=2) + "\n"
        imports.append(f'import "{manifest["resource_url"]}";\n')
    generated[THEMES / "sds200-cards.js"] = "".join(imports)
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, payload in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text() != payload:
                raise SystemExit(f"Generated HA asset differs: {path.relative_to(ROOT)}")
        else:
            path.write_text(payload)


if __name__ == "__main__":
    main()
